services:
  db:
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  adminer:
    ports:
      - "${ADMINER_HOST_PORT:-8080}:8080"
    networks:
      - default
    labels:
      - traefik.enable=false

  prestart:
    networks:
      - default

  backend:
    ports:
      - "${BACKEND_HOST_PORT:-8000}:8000"
    networks:
      - default
    labels:
      - traefik.enable=false

  frontend:
    ports:
      - "${FRONTEND_HOST_PORT:-5173}:80"
    build:
      args:
        - VITE_API_URL=http://localhost:${BACKEND_HOST_PORT:-8000}
        - NODE_ENV=production
    networks:
      - default
    labels:
      - traefik.enable=false

networks:
  traefik-public:
    external: false
