/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksAccessRouteImport } from './routes/tasks-access'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractorAccessRouteImport } from './routes/contractor-access'
import { Route as CleanerAccessRouteImport } from './routes/cleaner-access'
import { Route as CaretakerTasksRouteImport } from './routes/caretaker-tasks'
import { Route as CaretakerLoginRouteImport } from './routes/caretaker-login'
import { Route as CaretakerAccessRouteImport } from './routes/caretaker-access'
import { Route as BinsAccessRouteImport } from './routes/bins-access'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const TasksAccessRoute = TasksAccessRouteImport.update({
  id: '/tasks-access',
  path: '/tasks-access',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorAccessRoute = ContractorAccessRouteImport.update({
  id: '/contractor-access',
  path: '/contractor-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerAccessRoute = CleanerAccessRouteImport.update({
  id: '/cleaner-access',
  path: '/cleaner-access',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerTasksRoute = CaretakerTasksRouteImport.update({
  id: '/caretaker-tasks',
  path: '/caretaker-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerLoginRoute = CaretakerLoginRouteImport.update({
  id: '/caretaker-login',
  path: '/caretaker-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CaretakerAccessRoute = CaretakerAccessRouteImport.update({
  id: '/caretaker-access',
  path: '/caretaker-access',
  getParentRoute: () => rootRouteImport,
} as any)
const BinsAccessRoute = BinsAccessRouteImport.update({
  id: '/bins-access',
  path: '/bins-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/bins-access': typeof BinsAccessRoute
  '/caretaker-access': typeof CaretakerAccessRoute
  '/caretaker-login': typeof CaretakerLoginRoute
  '/caretaker-tasks': typeof CaretakerTasksRoute
  '/cleaner-access': typeof CleanerAccessRoute
  '/contractor-access': typeof ContractorAccessRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tasks-access': typeof TasksAccessRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/bins-access': typeof BinsAccessRoute
  '/caretaker-access': typeof CaretakerAccessRoute
  '/caretaker-login': typeof CaretakerLoginRoute
  '/caretaker-tasks': typeof CaretakerTasksRoute
  '/cleaner-access': typeof CleanerAccessRoute
  '/contractor-access': typeof ContractorAccessRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tasks-access': typeof TasksAccessRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/bins-access': typeof BinsAccessRoute
  '/caretaker-access': typeof CaretakerAccessRoute
  '/caretaker-login': typeof CaretakerLoginRoute
  '/caretaker-tasks': typeof CaretakerTasksRoute
  '/cleaner-access': typeof CleanerAccessRoute
  '/contractor-access': typeof ContractorAccessRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/tasks-access': typeof TasksAccessRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bins-access'
    | '/caretaker-access'
    | '/caretaker-login'
    | '/caretaker-tasks'
    | '/cleaner-access'
    | '/contractor-access'
    | '/dashboard'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/tasks-access'
    | '/admin'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bins-access'
    | '/caretaker-access'
    | '/caretaker-login'
    | '/caretaker-tasks'
    | '/cleaner-access'
    | '/contractor-access'
    | '/dashboard'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/tasks-access'
    | '/admin'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/bins-access'
    | '/caretaker-access'
    | '/caretaker-login'
    | '/caretaker-tasks'
    | '/cleaner-access'
    | '/contractor-access'
    | '/dashboard'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/tasks-access'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  BinsAccessRoute: typeof BinsAccessRoute
  CaretakerAccessRoute: typeof CaretakerAccessRoute
  CaretakerLoginRoute: typeof CaretakerLoginRoute
  CaretakerTasksRoute: typeof CaretakerTasksRoute
  CleanerAccessRoute: typeof CleanerAccessRoute
  ContractorAccessRoute: typeof ContractorAccessRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TasksAccessRoute: typeof TasksAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks-access': {
      id: '/tasks-access'
      path: '/tasks-access'
      fullPath: '/tasks-access'
      preLoaderRoute: typeof TasksAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-access': {
      id: '/contractor-access'
      path: '/contractor-access'
      fullPath: '/contractor-access'
      preLoaderRoute: typeof ContractorAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner-access': {
      id: '/cleaner-access'
      path: '/cleaner-access'
      fullPath: '/cleaner-access'
      preLoaderRoute: typeof CleanerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker-tasks': {
      id: '/caretaker-tasks'
      path: '/caretaker-tasks'
      fullPath: '/caretaker-tasks'
      preLoaderRoute: typeof CaretakerTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker-login': {
      id: '/caretaker-login'
      path: '/caretaker-login'
      fullPath: '/caretaker-login'
      preLoaderRoute: typeof CaretakerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caretaker-access': {
      id: '/caretaker-access'
      path: '/caretaker-access'
      fullPath: '/caretaker-access'
      preLoaderRoute: typeof CaretakerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bins-access': {
      id: '/bins-access'
      path: '/bins-access'
      fullPath: '/bins-access'
      preLoaderRoute: typeof BinsAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  BinsAccessRoute: BinsAccessRoute,
  CaretakerAccessRoute: CaretakerAccessRoute,
  CaretakerLoginRoute: CaretakerLoginRoute,
  CaretakerTasksRoute: CaretakerTasksRoute,
  CleanerAccessRoute: CleanerAccessRoute,
  ContractorAccessRoute: ContractorAccessRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TasksAccessRoute: TasksAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
